"""
Prompt templates for the LLM chat assistant (Telegram QnA only).

Trading signals are now generated by the rule-based RuleEngine, not the LLM.
The LLM's role is limited to: answering the trader's questions in plain English,
explaining why a trade fired, and summarising portfolio state.
"""

# Used by ChatEngine (chat_engine.py) — already has its own CHAT_SYSTEM_PROMPT.
# This file now only holds the market context template used to build the
# "TRADER CONTEXT" block injected into each chat turn.

CHAT_CONTEXT_TEMPLATE = """
Open Positions: {open_positions}
Today's P&L: ₹{daily_pnl}
Last Signal: {last_signal}
Watchlist Prices: {watchlist_prices}
Recent News Headlines: {news_headlines}
Active Strategy: {strategy_name}
"""
