intraday:
  - SBIN
  - WIPRO
  - IDEA
  - IRFC
  - NHPC
  - RECLTD
  - NMDC
  - SAIL
  - IDFCFIRSTB
  - SUZLON
  - RELIANCE
  - TCS
  - INFY

swing:
  - SBIN
  - WIPRO
  - IRFC
  - NHPC
  - SUZLON
  - RELIANCE
  - TCS
  - INFY
