intraday:
  - SBIN
  - ICICIBANK
  - HDFCBANK
  - AXISBANK
  - IDFCFIRSTB
  - RECLTD
  - RELIANCE
  - INFY
  - NHPC
  - NMDC
  - SAIL
  - SUZLON

swing:
  - SBIN
  - ICICIBANK
  - HDFCBANK
  - RELIANCE
  - INFY
  - NHPC
  - SUZLON
