"""
Unit tests for src/data/indicators.py — IndicatorEngine.

All tests use synthetic OHLCV data generated by the make_ohlcv_df helper.
No external data feeds or network access is required.
"""

from __future__ import annotations

import math
import numpy as np
import pandas as pd
import pytest

from src.data.indicators import IndicatorEngine, IndicatorResult


# ---------------------------------------------------------------------------
# Synthetic data factory
# ---------------------------------------------------------------------------


def make_ohlcv_df(n: int = 200, trend: str = "flat") -> pd.DataFrame:
    """
    Generate a synthetic OHLCV DataFrame with *n* rows.

    Parameters
    ----------
    n     : Number of candles to produce.
    trend : "up"   — prices rise monotonically with small noise
            "down" — prices fall monotonically with small noise
            "flat" — prices oscillate around a fixed level
    """
    rng = np.random.default_rng(seed=42)

    base = 500.0

    if trend == "up":
        # Steady uptrend: each close is ~0.3% higher than the previous.
        drift = np.linspace(0, n * 0.3, n)
        noise = rng.normal(0, 0.1, n)
        closes = base + drift + noise

    elif trend == "down":
        # Steady downtrend: each close is ~0.3% lower than the previous.
        drift = np.linspace(0, -(n * 0.3), n)
        noise = rng.normal(0, 0.1, n)
        closes = base + drift + noise

    else:  # "flat"
        # Oscillates around the base with moderate noise.
        noise = rng.normal(0, 2.0, n)
        closes = base + noise

    # Ensure prices are always positive.
    closes = np.clip(closes, 1.0, None)

    # Build OHLCV from closes; keep spreads realistic.
    spread = rng.uniform(0.2, 1.0, n)
    highs = closes + spread
    lows = np.clip(closes - spread, 0.1, None)
    opens = closes + rng.uniform(-0.5, 0.5, n)
    opens = np.clip(opens, lows, highs)
    volumes = rng.integers(100_000, 1_000_000, n).astype(float)

    timestamps = pd.date_range(
        start="2024-01-01 09:15:00",
        periods=n,
        freq="5min",
        tz="Asia/Kolkata",
    )

    return pd.DataFrame(
        {
            "timestamp": timestamps,
            "open": opens,
            "high": highs,
            "low": lows,
            "close": closes,
            "volume": volumes,
        }
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestIndicatorEngine:
    """Test suite for IndicatorEngine.compute()."""

    # ------------------------------------------------------------------
    # Fixture
    # ------------------------------------------------------------------

    @pytest.fixture
    def engine(self) -> IndicatorEngine:
        return IndicatorEngine()

    # ------------------------------------------------------------------
    # Guard: short DataFrames
    # ------------------------------------------------------------------

    def test_compute_returns_none_on_short_df(self, engine: IndicatorEngine) -> None:
        """DataFrames with fewer than 30 rows must return None, not raise."""
        for row_count in [0, 1, 10, 29]:
            df = make_ohlcv_df(n=row_count) if row_count > 0 else pd.DataFrame(
                columns=["timestamp", "open", "high", "low", "close", "volume"]
            )
            result = engine.compute(df, symbol="TEST")
            assert result is None, (
                f"Expected None for {row_count} rows, got {result!r}"
            )

    def test_compute_returns_none_on_none_df(self, engine: IndicatorEngine) -> None:
        """Passing None as df must return None safely."""
        result = engine.compute(None, symbol="TEST")  # type: ignore[arg-type]
        assert result is None

    # ------------------------------------------------------------------
    # Happy path: 200-row realistic DataFrame
    # ------------------------------------------------------------------

    def test_compute_returns_indicator_result(self, engine: IndicatorEngine) -> None:
        """200 rows of realistic OHLCV data must return a valid IndicatorResult."""
        df = make_ohlcv_df(n=200, trend="flat")
        result = engine.compute(df, symbol="RELIANCE")

        assert result is not None
        assert isinstance(result, IndicatorResult)
        assert result.symbol == "RELIANCE"
        assert isinstance(result.timestamp, (pd.Timestamp, type(None)))

    # ------------------------------------------------------------------
    # RSI range
    # ------------------------------------------------------------------

    def test_rsi_in_valid_range(self, engine: IndicatorEngine) -> None:
        """
        RSI(14) must be in [0, 100] for any trend that contains both up and down candles.

        A pure monotonic uptrend can produce RSI=NaN (no down-candles → avg_loss=0 →
        division by zero in the RS formula). We test with "flat" (always mixed) and
        "down" (losses dominate → RSI approaches 0 but stays numeric). We separately
        verify the "up" case via a mixed-noise dataset where NaN is not expected.
        """
        import math

        for trend in ("down", "flat"):
            df = make_ohlcv_df(n=200, trend=trend)
            result = engine.compute(df, symbol=f"SYM_{trend.upper()}")
            assert result is not None
            assert not math.isnan(result.rsi_14), (
                f"RSI is NaN for trend={trend!r}"
            )
            assert 0.0 <= result.rsi_14 <= 100.0, (
                f"RSI out of range for trend={trend!r}: {result.rsi_14}"
            )

        # For a mixed-noise uptrend (noise large enough to produce down-candles),
        # RSI should also be finite and in range.
        rng = np.random.default_rng(seed=99)
        n = 200
        closes = 500.0 + np.linspace(0, 30, n) + rng.normal(0, 2.0, n)
        spread = rng.uniform(0.2, 1.0, n)
        highs = closes + spread
        lows = np.clip(closes - spread, 0.1, None)
        opens = np.clip(closes + rng.uniform(-0.5, 0.5, n), lows, highs)
        volumes = rng.integers(100_000, 1_000_000, n).astype(float)
        timestamps = pd.date_range("2024-01-01 09:15", periods=n, freq="5min", tz="Asia/Kolkata")
        mixed_df = pd.DataFrame({
            "timestamp": timestamps, "open": opens, "high": highs,
            "low": lows, "close": closes, "volume": volumes,
        })
        result = engine.compute(mixed_df, symbol="SYM_MIXED_UP")
        assert result is not None
        assert not math.isnan(result.rsi_14), "RSI is NaN for mixed uptrend"
        assert 0.0 <= result.rsi_14 <= 100.0, f"RSI out of range: {result.rsi_14}"

    # ------------------------------------------------------------------
    # MACD histogram identity
    # ------------------------------------------------------------------

    def test_macd_histogram_equals_line_minus_signal(
        self, engine: IndicatorEngine
    ) -> None:
        """macd_hist must equal macd_line − macd_signal within float precision."""
        df = make_ohlcv_df(n=200, trend="flat")
        result = engine.compute(df, symbol="TEST")
        assert result is not None

        expected_hist = result.macd_line - result.macd_signal
        assert math.isclose(result.macd_hist, expected_hist, rel_tol=1e-9, abs_tol=1e-12), (
            f"MACD histogram identity violated: "
            f"hist={result.macd_hist}, line-signal={expected_hist}"
        )

    # ------------------------------------------------------------------
    # EMA ordering — uptrend
    # ------------------------------------------------------------------

    def test_ema_ordering_uptrend(self, engine: IndicatorEngine) -> None:
        """
        When prices rise steadily ema_9 > ema_21 > ema_50 and
        the trend string must be 'UPTREND'.
        """
        df = make_ohlcv_df(n=200, trend="up")
        result = engine.compute(df, symbol="UPTREND_SYM")
        assert result is not None

        assert result.ema_9 > result.ema_21, (
            f"Expected ema_9 > ema_21 in uptrend: {result.ema_9} <= {result.ema_21}"
        )
        assert result.ema_21 > result.ema_50, (
            f"Expected ema_21 > ema_50 in uptrend: {result.ema_21} <= {result.ema_50}"
        )
        assert result.trend == "UPTREND", (
            f"Expected trend='UPTREND', got '{result.trend}'"
        )

    # ------------------------------------------------------------------
    # EMA ordering — downtrend
    # ------------------------------------------------------------------

    def test_ema_ordering_downtrend(self, engine: IndicatorEngine) -> None:
        """
        When prices fall steadily ema_9 < ema_21 < ema_50 and
        the trend string must be 'DOWNTREND'.
        """
        df = make_ohlcv_df(n=200, trend="down")
        result = engine.compute(df, symbol="DOWNTREND_SYM")
        assert result is not None

        assert result.ema_9 < result.ema_21, (
            f"Expected ema_9 < ema_21 in downtrend: {result.ema_9} >= {result.ema_21}"
        )
        assert result.ema_21 < result.ema_50, (
            f"Expected ema_21 < ema_50 in downtrend: {result.ema_21} >= {result.ema_50}"
        )
        assert result.trend == "DOWNTREND", (
            f"Expected trend='DOWNTREND', got '{result.trend}'"
        )

    # ------------------------------------------------------------------
    # Bollinger Bands ordering
    # ------------------------------------------------------------------

    def test_bollinger_bands_ordering(self, engine: IndicatorEngine) -> None:
        """bb_lower < bb_mid < bb_upper must hold for all market conditions."""
        for trend in ("up", "down", "flat"):
            df = make_ohlcv_df(n=200, trend=trend)
            result = engine.compute(df, symbol="BB_TEST")
            assert result is not None

            assert result.bb_lower < result.bb_mid, (
                f"bb_lower >= bb_mid for trend={trend!r}: "
                f"{result.bb_lower} >= {result.bb_mid}"
            )
            assert result.bb_mid < result.bb_upper, (
                f"bb_mid >= bb_upper for trend={trend!r}: "
                f"{result.bb_mid} >= {result.bb_upper}"
            )

    # ------------------------------------------------------------------
    # Relative volume
    # ------------------------------------------------------------------

    def test_relative_volume_positive(self, engine: IndicatorEngine) -> None:
        """relative_volume must be strictly positive when volume data exists."""
        df = make_ohlcv_df(n=200, trend="flat")
        result = engine.compute(df, symbol="VOL_TEST")
        assert result is not None
        assert result.relative_volume > 0.0, (
            f"Expected relative_volume > 0, got {result.relative_volume}"
        )

    # ------------------------------------------------------------------
    # Missing columns guard
    # ------------------------------------------------------------------

    def test_compute_returns_none_on_missing_columns(
        self, engine: IndicatorEngine
    ) -> None:
        """A DataFrame missing required OHLCV columns must return None."""
        df = make_ohlcv_df(n=200).drop(columns=["volume"])
        result = engine.compute(df, symbol="BADCOLS")
        assert result is None

    # ------------------------------------------------------------------
    # Symbol propagation
    # ------------------------------------------------------------------

    def test_symbol_propagated_to_result(self, engine: IndicatorEngine) -> None:
        """The symbol passed to compute() must appear unchanged in the result."""
        df = make_ohlcv_df(n=200)
        symbol = "TCS"
        result = engine.compute(df, symbol=symbol)
        assert result is not None
        assert result.symbol == symbol

    # ------------------------------------------------------------------
    # ATR is positive
    # ------------------------------------------------------------------

    def test_atr_is_positive(self, engine: IndicatorEngine) -> None:
        """ATR(14) must always be strictly positive for real OHLCV data."""
        df = make_ohlcv_df(n=200, trend="flat")
        result = engine.compute(df, symbol="ATR_TEST")
        assert result is not None
        assert result.atr_14 > 0.0, f"Expected ATR > 0, got {result.atr_14}"

    # ------------------------------------------------------------------
    # VWAP is positive
    # ------------------------------------------------------------------

    def test_vwap_is_positive(self, engine: IndicatorEngine) -> None:
        """VWAP must be positive for positive price data."""
        df = make_ohlcv_df(n=200, trend="flat")
        result = engine.compute(df, symbol="VWAP_TEST")
        assert result is not None
        assert result.vwap > 0.0, f"Expected VWAP > 0, got {result.vwap}"

    # ------------------------------------------------------------------
    # price_vs_vwap consistency
    # ------------------------------------------------------------------

    def test_price_vs_vwap_consistent(self, engine: IndicatorEngine) -> None:
        """price_vs_vwap string must match actual close vs. VWAP relationship."""
        df = make_ohlcv_df(n=200, trend="flat")
        result = engine.compute(df, symbol="PVV_TEST")
        assert result is not None

        if result.close >= result.vwap:
            assert result.price_vs_vwap == "ABOVE_VWAP"
        else:
            assert result.price_vs_vwap == "BELOW_VWAP"

    # ------------------------------------------------------------------
    # to_dict serialisability
    # ------------------------------------------------------------------

    def test_to_dict_returns_serialisable_dict(self, engine: IndicatorEngine) -> None:
        """to_dict() must return a plain dict with all expected keys."""
        df = make_ohlcv_df(n=200)
        result = engine.compute(df, symbol="DICT_TEST")
        assert result is not None

        d = result.to_dict()
        assert isinstance(d, dict)

        expected_keys = {
            "symbol", "timestamp", "close", "rsi_14",
            "macd_line", "macd_signal", "macd_hist",
            "ema_9", "ema_21", "ema_50", "ema_200",
            "bb_upper", "bb_mid", "bb_lower", "bb_pct_b",
            "atr_14", "volume_sma_20", "relative_volume",
            "vwap", "trend", "price_vs_vwap",
        }
        assert expected_keys.issubset(d.keys()), (
            f"Missing keys in to_dict() output: {expected_keys - d.keys()}"
        )
        # Timestamp should be converted to a string
        assert isinstance(d["timestamp"], str), (
            f"Expected timestamp as str, got {type(d['timestamp'])}"
        )

    # ------------------------------------------------------------------
    # Exactly 30 rows (boundary: minimum allowed)
    # ------------------------------------------------------------------

    def test_compute_succeeds_at_minimum_row_count(
        self, engine: IndicatorEngine
    ) -> None:
        """A DataFrame with exactly 30 rows (the minimum) must not return None."""
        df = make_ohlcv_df(n=30)
        result = engine.compute(df, symbol="BOUNDARY")
        assert result is not None
